<?php
/**
 * Cloud Team Management - Export Assignments to Excel
 */

require_once __DIR__ . '/../../vendor/autoload.php';
require_once __DIR__ . '/../../config/database.php';
require_once __DIR__ . '/../../config/auth.php';
require_once __DIR__ . '/../../config/activity_helper.php';
require_once __DIR__ . '/../helper.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

// Enforce login
requireLogin();
$currentUser = getCurrentUser();

$db = Database::getConnection();

// Get project filter
$projectIdFilter = isset($_GET['project_id']) && is_numeric($_GET['project_id']) ? (int)$_GET['project_id'] : 0;

$where = '';
$params = [];

if ($projectIdFilter > 0) {
    $where = ' WHERE p.id = :project_id ';
    $params['project_id'] = $projectIdFilter;
}

// Fetch assignments
try {
    $sql = "
        SELECT a.nama, a.nim, p.nama_proyek, ap.created_at
        FROM anggota_proyek ap
        JOIN anggota a ON ap.anggota_id = a.id
        JOIN proyek p ON ap.proyek_id = p.id
        " . $where . "
        ORDER BY p.nama_proyek ASC, a.nama ASC
    ";
    $stmt = $db->prepare($sql);
    $stmt->execute($params);
    $assignments = $stmt->fetchAll();
} catch (PDOException $e) {
    die("Database Error: " . $e->getMessage());
}

// Fetch project name for log & title
$projectNameLabel = 'Semua Proyek';
if ($projectIdFilter > 0) {
    try {
        $pStmt = $db->prepare("SELECT nama_proyek FROM proyek WHERE id = ?");
        $pStmt->execute([$projectIdFilter]);
        $fetchedName = $pStmt->fetchColumn();
        if ($fetchedName) {
            $projectNameLabel = $fetchedName;
        }
    } catch (PDOException $e) {
        error_log("Failed to fetch project name: " . $e->getMessage());
    }
}

// Write activity log with detailed description
if ($projectIdFilter > 0) {
    writeLog($db, $_SESSION['user_id'], 'EXPORT_ASSIGNMENT_EXCEL', 'Mengunduh laporan assignment (Excel) proyek: ' . $projectNameLabel);
} else {
    writeLog($db, $_SESSION['user_id'], 'EXPORT_ASSIGNMENT_EXCEL', 'Mengunduh laporan assignment (Excel) untuk semua proyek');
}

// Initialize Spreadsheet
$spreadsheet = new Spreadsheet();

// 1. Setup Assignments Sheet
$sheet = $spreadsheet->getActiveSheet();
$sheet->setTitle('Assignments');

// Set Headers
$sheet->setCellValue('A1', 'No');
$sheet->setCellValue('B1', 'Nama Anggota');
$sheet->setCellValue('C1', 'NIM');
$sheet->setCellValue('D1', 'Nama Proyek');
$sheet->setCellValue('E1', 'Ditugaskan Pada');

// Make Headers Bold
$sheet->getStyle('A1:E1')->getFont()->setBold(true);

// Populate Data
$rowNumber = 2;
$no = 1;
foreach ($assignments as $a) {
    $sheet->setCellValue('A' . $rowNumber, $no++);
    $sheet->setCellValue('B' . $rowNumber, $a['nama']);
    $sheet->setCellValue('C' . $rowNumber, $a['nim']);
    $sheet->setCellValue('D' . $rowNumber, $a['nama_proyek']);
    $sheet->setCellValue('E' . $rowNumber, date('Y-m-d H:i:s', strtotime($a['created_at'])));
    $rowNumber++;
}

// Auto-size columns for Assignments sheet
foreach (range('A', 'E') as $col) {
    $sheet->getColumnDimension($col)->setAutoSize(true);
}

// 2. Setup Metadata Sheet
$metaSheet = $spreadsheet->createSheet();
$metaSheet->setTitle('Metadata');

// Set Metadata
$metaSheet->setCellValue('A1', 'Metadata Key');
$metaSheet->setCellValue('B1', 'Value');
$metaSheet->getStyle('A1:B1')->getFont()->setBold(true);

$metaSheet->setCellValue('A2', 'Generated By');
$metaSheet->setCellValue('B2', htmlspecialchars($currentUser['nama'] ?? $currentUser['username']));

$metaSheet->setCellValue('A3', 'Generated At');
$metaSheet->setCellValue('B3', formatExportDate('now'));

$metaSheet->setCellValue('A4', 'Project Filter');
$metaSheet->setCellValue('B4', $projectNameLabel);

$metaSheet->getStyle('A2:A4')->getFont()->setBold(true);

$metaSheet->getColumnDimension('A')->setAutoSize(true);
$metaSheet->getColumnDimension('B')->setAutoSize(true);

// Reset default focus back to Assignments tab
$spreadsheet->setActiveSheetIndex(0);

// Headers to trigger download
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment; filename="Laporan_Assignment_' . date('Ymd_His') . '.xlsx"');
header('Cache-Control: max-age=0');

$writer = new Xlsx($spreadsheet);
$writer->save('php://output');
exit;
