<?php
/**
 * Cloud Team Management - Export Members to Excel
 */

require_once __DIR__ . '/../../vendor/autoload.php';
require_once __DIR__ . '/../../config/database.php';
require_once __DIR__ . '/../../config/auth.php';
require_once __DIR__ . '/../../config/activity_helper.php';
require_once __DIR__ . '/../helper.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

// Protect page (Admin only)
requireRole('admin');
$currentUser = getCurrentUser();

$db = Database::getConnection();

// Fetch members
try {
    $members = $db->query("SELECT * FROM anggota ORDER BY nama ASC")->fetchAll();
} catch (PDOException $e) {
    die("Database Error: " . $e->getMessage());
}

// Write activity log
writeLog($db, $_SESSION['user_id'], 'EXPORT_MEMBER_EXCEL', 'Mengunduh laporan data anggota (Excel)');

// Initialize Spreadsheet
$spreadsheet = new Spreadsheet();

// 1. Setup Active Sheet (Members Data)
$sheet = $spreadsheet->getActiveSheet();
$sheet->setTitle('Members');

// Set Headers
$sheet->setCellValue('A1', 'No');
$sheet->setCellValue('B1', 'Nama Lengkap');
$sheet->setCellValue('C1', 'NIM');
$sheet->setCellValue('D1', 'Email');

// Make Headers Bold
$sheet->getStyle('A1:D1')->getFont()->setBold(true);

// Populate Data
$rowNumber = 2;
$no = 1;
foreach ($members as $m) {
    $sheet->setCellValue('A' . $rowNumber, $no++);
    $sheet->setCellValue('B' . $rowNumber, $m['nama']);
    $sheet->setCellValue('C' . $rowNumber, $m['nim']);
    $sheet->setCellValue('D' . $rowNumber, $m['email']);
    $rowNumber++;
}

// Auto-size columns for Members sheet
foreach (range('A', 'D') as $col) {
    $sheet->getColumnDimension($col)->setAutoSize(true);
}

// 2. Setup Metadata Sheet
$metaSheet = $spreadsheet->createSheet();
$metaSheet->setTitle('Metadata');

// Set Metadata Headers & Info
$metaSheet->setCellValue('A1', 'Metadata Key');
$metaSheet->setCellValue('B1', 'Value');
$metaSheet->getStyle('A1:B1')->getFont()->setBold(true);

$metaSheet->setCellValue('A2', 'Generated By');
$metaSheet->setCellValue('B2', htmlspecialchars($currentUser['nama'] ?? $currentUser['username']));

$metaSheet->setCellValue('A3', 'Generated At');
$metaSheet->setCellValue('B3', formatExportDate('now'));

$metaSheet->setCellValue('A4', 'Role');
$metaSheet->setCellValue('B4', strtoupper(htmlspecialchars($currentUser['role'])));

// Format Metadata labels
$metaSheet->getStyle('A2:A4')->getFont()->setBold(true);

// Auto-size columns for Metadata sheet
$metaSheet->getColumnDimension('A')->setAutoSize(true);
$metaSheet->getColumnDimension('B')->setAutoSize(true);

// Set default focus back to Members tab
$spreadsheet->setActiveSheetIndex(0);

// Headers to trigger .xlsx download
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment; filename="Laporan_Anggota_' . date('Ymd_His') . '.xlsx"');
header('Cache-Control: max-age=0');

$writer = new Xlsx($spreadsheet);
$writer->save('php://output');
exit;
