<?php
/**
 * Cloud Team Management - Export Projects to Excel
 */

require_once __DIR__ . '/../../vendor/autoload.php';
require_once __DIR__ . '/../../config/database.php';
require_once __DIR__ . '/../../config/auth.php';
require_once __DIR__ . '/../../config/activity_helper.php';
require_once __DIR__ . '/../helper.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

// Enforce login
requireLogin();
$currentUser = getCurrentUser();

$db = Database::getConnection();

// Get status filter
$statusFilter = trim($_GET['status'] ?? 'all');
$allowedStatuses = ['direncanakan', 'berjalan', 'selesai', 'tertunda'];

$where = '';
$params = [];

if (in_array($statusFilter, $allowedStatuses)) {
    $where = ' WHERE p.status = :status ';
    $params['status'] = $statusFilter;
}

// Fetch projects
try {
    $sql = "
        SELECT p.*, COUNT(ap.id) as total_anggota
        FROM proyek p
        LEFT JOIN anggota_proyek ap ON p.id = ap.proyek_id
        " . $where . "
        GROUP BY p.id
        ORDER BY p.nama_proyek ASC
    ";
    $stmt = $db->prepare($sql);
    $stmt->execute($params);
    $projects = $stmt->fetchAll();
} catch (PDOException $e) {
    die("Database Error: " . $e->getMessage());
}

// Write activity log with detail filter
$statusLabel = 'Semua Status';
if (in_array($statusFilter, $allowedStatuses)) {
    $statusLabel = getProjectStatusText($statusFilter);
}
writeLog($db, $_SESSION['user_id'], 'EXPORT_PROJECT_EXCEL', 'Mengunduh laporan proyek (Excel) dengan filter status: ' . $statusLabel);

// Initialize Spreadsheet
$spreadsheet = new Spreadsheet();

// 1. Setup Projects Sheet
$sheet = $spreadsheet->getActiveSheet();
$sheet->setTitle('Projects');

// Set Headers
$sheet->setCellValue('A1', 'No');
$sheet->setCellValue('B1', 'Nama Proyek');
$sheet->setCellValue('C1', 'Status');
$sheet->setCellValue('D1', 'Deadline');
$sheet->setCellValue('E1', 'Total Anggota');

// Make Headers Bold
$sheet->getStyle('A1:E1')->getFont()->setBold(true);

// Populate Data
$rowNumber = 2;
$no = 1;
foreach ($projects as $p) {
    $sheet->setCellValue('A' . $rowNumber, $no++);
    $sheet->setCellValue('B' . $rowNumber, $p['nama_proyek']);
    $sheet->setCellValue('C' . $rowNumber, getProjectStatusText($p['status']));
    $sheet->setCellValue('D' . $rowNumber, date('Y-m-d', strtotime($p['deadline'])));
    $sheet->setCellValue('E' . $rowNumber, $p['total_anggota'] . ' Org');
    $rowNumber++;
}

// Auto-size columns for Projects sheet
foreach (range('A', 'E') as $col) {
    $sheet->getColumnDimension($col)->setAutoSize(true);
}

// 2. Setup Metadata Sheet
$metaSheet = $spreadsheet->createSheet();
$metaSheet->setTitle('Metadata');

// Set Metadata
$metaSheet->setCellValue('A1', 'Metadata Key');
$metaSheet->setCellValue('B1', 'Value');
$metaSheet->getStyle('A1:B1')->getFont()->setBold(true);

$metaSheet->setCellValue('A2', 'Generated By');
$metaSheet->setCellValue('B2', htmlspecialchars($currentUser['nama'] ?? $currentUser['username']));

$metaSheet->setCellValue('A3', 'Generated At');
$metaSheet->setCellValue('B3', formatExportDate('now'));

$metaSheet->setCellValue('A4', 'Status Filter');
$metaSheet->setCellValue('B4', $statusLabel);

$metaSheet->getStyle('A2:A4')->getFont()->setBold(true);

$metaSheet->getColumnDimension('A')->setAutoSize(true);
$metaSheet->getColumnDimension('B')->setAutoSize(true);

// Reset default focus back to Projects tab
$spreadsheet->setActiveSheetIndex(0);

// Headers to trigger download
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment; filename="Laporan_Proyek_' . date('Ymd_His') . '.xlsx"');
header('Cache-Control: max-age=0');

$writer = new Xlsx($spreadsheet);
$writer->save('php://output');
exit;
